version: "3.8"
services:
  chat-bot-api:
    build:
      context: .
    ports:
      - 8000:8000
    networks:
      - chatbot-network
    volumes:
      - .:/chat-bot
networks:
  chatbot-network:
    driver: bridge
