version: "3.8"
services:
  chat-bot-api:
    build:
      context: .
    ports:
      - 8000:8000
    networks:
      - chatbot-network
    volumes:
      - .:/chat-bot
  # bot:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - chat-bot-api
  #   networks:
  #     - chatbot-network
networks:
  chatbot-network:
    driver: bridge
